---
title: "Diversity Project Abundances"
author: "Joshua"
date: "4/1/2021"
output: html_document
---

```{r}
rm(list=ls())
```

# Importing data into R

```{r}
site_species <- read.csv("alpine_ridge_data/OTU_table.csv", header = TRUE)
site_species.t <- t(site_species)
```

#Rarefaction

```{r}
#Visualization of rarecurves for all samples
library(vegan)
richness <- rowSums((site_species.t > 0) * 1)
print(richness)
minimum.r <- min(rowSums(site_species.t))
rarefy <- rarefy(x = site_species.t, sample = minimum.r, se = TRUE)

rarecurve(x = site_species.t, step = 20, col = "blue", cex = .6, las = 1)
abline(0, 1, col = 'red')
text(200, 100, "1:1", pos = 2, col = 'red')
```
```{r}
#Rarefaction of samples
site_species.r <- rrarefy(site_species.t, 1000)

richness <- rowSums((site_species.r > 0) * 1)
minimum.r <- min(rowSums(site_species.r))
rarefy <- rarefy(x = site_species.r, sample = minimum.r, se = TRUE)

rarecurve(x = site_species.r, step = 20, col = "blue", cex = .6, las = 1)
abline(0, 1, col = 'red')
text(200, 100, "1:1", pos = 2, col = 'red')
```
```{r}
#Remove samples containing less than 1000 reads (R1.14, R1.55.2, R2.25, S2.78.2)

df.site_species.r <- as.data.frame(site_species.r)
rarefied_site_species <- data.frame()

for (i in 1:nrow(df.site_species.r)){
  if (rowSums(df.site_species.r[i,]) >= 1000){
    rarefied_site_species <- rbind(rarefied_site_species, df.site_species.r[i,])
  }
}

#Visualizing
richness <- rowSums((rarefied_site_species > 0) * 1)
minimum.r <- min(rowSums(rarefied_site_species))
rarefy <- rarefy(x = rarefied_site_species, sample = minimum.r, se = TRUE)

rarecurve(x = rarefied_site_species, step = 20, col = "blue", cex = .6, las = 1)
abline(0, 1, col = 'red')
text(200, 100, "1:1", pos = 2, col = 'red')
```
# Calculating Beta-Diversity 

```{r}
fungalBC <- vegdist(rarefied_site_species, method = "bray")
print(fungalBC)
```


# Cluster Analysis of Fungal Communities

```{r} 
#Performing Cluster Analysis
fungal.ward <- hclust(fungalBC, method = "ward.D2")

#Plotting Cluster
par(mar = c(1,5,2,2) + .1)
plot(fungal.ward, main = "Doubs River Fish: Ward's Clustering",
     ylab = "Squared Bray-Curtis Distance")
```


# PCoA of Fungal Communities

```{r}
fungal.pcoa <- cmdscale(fungalBC, eig = TRUE, k = 3)

explainvar1 <- round(fungal.pcoa$eig[1]/sum(fungal.pcoa$eig), 3) * 100
explainvar2 <- round(fungal.pcoa$eig[2]/sum(fungal.pcoa$eig), 3) * 100
explainvar3 <- round(fungal.pcoa$eig[3]/sum(fungal.pcoa$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)

#Define Plot Parameters
par(mar = c(5,5,1,2), .1)

#Initiate Plot
plot(fungal.pcoa$points[,1], fungal.pcoa$points[,2], ylim = c(-.2, .7),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)

#Add axis 
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

#Add Points & Labels
points(fungal.pcoa$points[,1], fungal.pcoa$points[,2],
       pch = 19, cex = 3, bg = "gray", col = "gray")
text(fungal.pcoa$points[,1], fungal.pcoa$points[,2],
     labels = row.names(fungal.pcoa$points))

```
## Relative Abundance Visualization

```{r}
genus <- read.csv("alpine_ridge_data/genus_table.csv", header = TRUE)
# Converting to Long Format
library(reshape2)
genus_long <- melt(genus, id.vars = "Genus", variable.name = "Sample")

# Creating Graph of data
library(ggplot2)
genus_graph <- ggplot(data = genus_long, mapping = aes(x = Sample,  y = value, fill = Genus))
genus_graph <- genus_graph + geom_bar(stat="identity")
genus_graph <- genus_graph + labs(y = "Relative Abundance", x = "Sample", title = "Genus Relative Abundances") + theme_classic()
genus_graph <- genus_graph + theme(legend.position = "None")
genus_graph <- genus_graph + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
genus_graph
```





